/** Declaration file generated by dts-gen */
export interface Literal {
  type: "literal";
  value: number;
}

export type BinaryOperators = "+" | "-" | "*" | "/";
export interface BinaryOperation {
  type: "binary";
  operator: BinaryOperators;
  left: Expression;
  right: Expression;
}

export type Expression = Literal | BinaryOperation;

export function assertNever(e: string, r: string): void;

export function evaluate(t: Expression): number;
